apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-routing-consumer-hello
spec:
  rules:
    - host: consumer.hello.sidartasilva.io
      http:
        paths:
          - path: /
            backend:
              serviceName: project007
              servicePort: 8081
